auth_app/urls.py
from django.urls import path
from . import views


app_name = 'authentication'
urlpatterns = [
    path('student_login/', views.StudentLoginForm.as_view(), name='stu_login'),
    path('student_logout/', views.StudentLogout.as_view(), name='stu_logout'),
    path('staff/login/', views.StaffLoginForm.as_view(), name='staff_login'),
    path('staff/logout/', views.StaffLogout.as_view(), name='staff_logout'),
]

college/urls.py
from django.urls import path
from college import views

app_name = 'college'
urlpatterns = [
    path('index/', views.IndexPage.as_view(), name='index'),
    path('departments/', views.DepartmentList.as_view(), name='depts'),
    path('<str:dept>/department/', views.DepartmentStudentView.as_view(), name='d_std'),



    path('download-users-csv/', views.download_user_details_csv, name='download_users_csv'),
    path('browse_csv/', views.browse_csv, name='browse_csv'),
    path('upload_csv/', views.upload_csv, name='upload_csv'),
]

college_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('college.urls')),
    path('auth/', include('auth_app.urls')),
    path('student/', include('student_info.urls')),
    path('staff/', include('staff_info.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff_info/urls.py
from django.urls import path
from . import views


app_name = 'staff'
urlpatterns = [
    path('registration/', views.StaffRegistrationPage.as_view(), name='staff_reg'),
    path('dashboard/', views.StaffDetailView.as_view(), name='staff_detail'),
    path('staff_list/', views.StaffListView.as_view(), name='staff_list'),
]

student_info/urls.py
from django.urls import path
from . import views


app_name = 'student'
urlpatterns = [
    path('student_application_form/', views.StudentApplicationPage.as_view(), name='stu_application_form'),
    path('student_registration/', views.StudentRegistrationPage.as_view(), name='stu_reg'),
    path('stu_dashboard/', views.StudentDashboard.as_view(), name='stu_dashboard'),
    path('<str:dept>/students/', views.StudentListView.as_view(), name='dept_students'),
    path('<str:dept>/staff/', views.StaffList.as_view(), name='staff'),
    path('success/', views.success, name='success'),

]

college/models.py
from django.db import models

# Create your models here.

college/forms.py
from django import forms


class UploadCSVForm(forms.Form):
    csv_file = forms.FileField()

college/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
import pandas as pd
from student_info.models import Department, StudentProfile
from django.views.generic import ListView
from django.views import View
from auth_app.mixins import StaffLoginRequiredMixin


class IndexPage(TemplateView):
    template_name = 'college/index.html'


class DepartmentList(StaffLoginRequiredMixin,ListView):
    model = Department
    template_name = 'college/departments.html'
    context_object_name = 'depts'


class DepartmentStudentView(StaffLoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        students_list = StudentProfile.objects.filter(application__department__code=kwargs['dept'])
        return render(self.request, 'college/dept_students.html', {'students':students_list})



from django.http import HttpResponse
from auth_app.models import MyUser
import pandas as pd

def download_user_details_csv(request):
    users = MyUser.objects.all()

    data = {
        'Email':[user.email for user in users],
        'Mobile_number' : [user.mobile_number for user in users],
        'Is Student' : [ "Student" if user.is_student else "Staff" for user in users]
    }

    df = pd.DataFrame(data)

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="user_details.csv"'

    df.to_csv(response)

    return response


def browse_csv(request):
    # Assuming you have a csv file
    excel_file = r"C:\Users\lenovo\Downloads\Sample - Superstore.xls"
    # import ipdb;ipdb.set_trace(context=15)
    df = pd.read_excel(excel_file)
    data = df.to_dict('records')  # Convert DataFrame to list of dictionaries
    columns = df.columns.tolist()  # Get column names
    return render(request, 'college/browse_csv.html', {'data': data[99:120], 'columns': columns})

    
from .forms import UploadCSVForm

def upload_csv(request):
    if request.method == "POST":
        form = UploadCSVForm(request.POST, request.FILES)
        if form.is_valid():
            print(request.FILES)
            
            csv_file = form.cleaned_data['csv_file']

            data = pd.read_excel(csv_file)
            return render(request, 'college/upload_cvs.html', {'data':data})
    else:
        form = UploadCSVForm()
        return render(request, 'college/upload_csv.html', {'form':form})

college/templates/college/browse_csv.html
{% load custom_filters %}

<!DOCTYPE html>
<html>
<head>
    <title>Browsable CSV</title>
</head>
<body>
    <h1>CSV Data</h1>
    <table>
        <thead>
            <tr>
                {% for col in columns %}
                    <th>{{ col }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
                <tr>
                    {% for col in columns %}
                        <td>{{ row|small:col }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

college/templates/college/departments.html
{% if depts %}
    {% for dept in depts %}
        <a href="{% url 'college:d_std' dept %}"><p>{{dept}}</p></a>
    {% endfor %}
{% else %}
    <h1>Departments are Found.</h1>
{% endif %}

<br><hr><br>
<a href="{% url 'staff:staff_detail' %}">Back</a><br>
<a href="{% url 'authentication:staff_logout' %}">Logout</a>

college/templates/college/dept_students.html
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Roll Number</th>
            <th>Mobile Number</th>
            <th>Intermediate</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
            <tr>
                <td>{{student.applicaton.name}}</td>
                <td>{{student.user.email}}</td>
                <td>{{student.id}}</td>
                <td>{{student.application.intermediate}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<br><hr><br>
<a href="{% url 'college:depts' %}">Back</a><br>
<a href="{% url 'authentication:staff_logout' %}">Logout</a>

college/templates/college/index.html
<a href="{% url 'student:stu_application_form' %}">Student Application</a><br>
<a href="{% url 'student:stu_reg' %}">Student Registration</a><br>
<a href="{% url 'authentication:stu_login' %}">Student Login</a><br>
<a href="{% url 'staff:staff_reg' %}">Staff Registration</a><br>
<a href="{% url 'authentication:staff_login' %}">Staff Login</a><br>

<a href="{% url 'college:download_users_csv' %}">Download Users Data</a>


<br><hr><br>
<a href="{% url 'college:browse_csv' %}">Browse csv file</a><br><br>
<a href="{% url 'college:upload_csv' %}">Upload csv and use browsable csv</a>

college/templates/college/upload_csv.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% if data %}
    {% for row in data %}
        {{row}}
    {% endfor %}
{% endif %}