auth_app/urls.py
from django.urls import path
from . import views


app_name = 'authentication'
urlpatterns = [
    path('student_login/', views.StudentLoginForm.as_view(), name='stu_login'),
    path('student_logout/', views.StudentLogout.as_view(), name='stu_logout'),
    path('staff/login/', views.StaffLoginForm.as_view(), name='staff_login'),
    path('staff/logout/', views.StaffLogout.as_view(), name='staff_logout'),
]

college/urls.py
from django.urls import path
from college import views

app_name = 'college'
urlpatterns = [
    path('index/', views.IndexPage.as_view(), name='index'),
    path('departments/', views.DepartmentList.as_view(), name='depts'),
    path('<str:dept>/department/', views.DepartmentStudentView.as_view(), name='d_std'),



    path('download-users-csv/', views.download_user_details_csv, name='download_users_csv'),
    path('browse_csv/', views.browse_csv, name='browse_csv'),
    path('upload_csv/', views.upload_csv, name='upload_csv'),
]

college_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('college.urls')),
    path('auth/', include('auth_app.urls')),
    path('student/', include('student_info.urls')),
    path('staff/', include('staff_info.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student_info/urls.py
from django.urls import path
from . import views


app_name = 'student'
urlpatterns = [
    path('student_application_form/', views.StudentApplicationPage.as_view(), name='stu_application_form'),
    path('student_registration/', views.StudentRegistrationPage.as_view(), name='stu_reg'),
    path('stu_dashboard/', views.StudentDashboard.as_view(), name='stu_dashboard'),
    path('<str:dept>/students/', views.StudentListView.as_view(), name='dept_students'),
    path('<str:dept>/staff/', views.StaffList.as_view(), name='staff'),
    path('success/', views.success, name='success'),

]

student_info/models.py
from django.db import models
from auth_app.models import MyUser


class Department(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=10)

    def __str__(self):
        return self.code
    

class StudentApplication(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    ssc = models.FloatField()
    intermediate = models.IntegerField()
    department = models.ForeignKey(Department, on_delete = models.SET_NULL, blank=True, null=True)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} {self.email}"


Nationality_Choices = (
    ('IND', 'India'),
    ('USA', 'United States of America'),
)


GENDER = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('Other', 'Transgender'),
)


class StudentProfile(models.Model):
    gender = models.CharField(max_length=5,choices = GENDER)
    dob = models.DateField()
    nationality = models.CharField(max_length=5, choices = Nationality_Choices)
    profile_pic = models.ImageField(upload_to='Student Profiles')
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    application = models.OneToOneField(StudentApplication, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email
    

student_info/forms.py
from django import forms
from .models import StudentApplication, StudentProfile, GENDER, Nationality_Choices
from django.core.exceptions import ValidationError

class StudentApplicationForm(forms.ModelForm):
    class Meta:
        model = StudentApplication
        exclude = ('is_approved',)


class StudentProfileForm(forms.Form):
    gender = forms.CharField()
    dob = forms.DateField()
    nationality = forms.CharField()
    profile_pic = forms.ImageField()
    



class StudentRegistrationForm(forms.Form):
    email = forms.EmailField()
    gender = forms.ChoiceField(choices=GENDER)
    dob = forms.DateField()
    nationality = forms.ChoiceField(choices=Nationality_Choices)
    profile_pic = forms.ImageField()
    mobile_number = forms.IntegerField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_email(self):
        data = self.cleaned_data['email']
        stu_applications = [ obj[0] for obj in StudentApplication.objects.all().values_list(('email'))]
        student_profiles = StudentProfile.objects.all() 
        stu_registrations = [ stu.user.email for stu in student_profiles] if student_profiles else []
        if len(stu_registrations) < 100:
            if data in stu_applications:
                student_application = StudentApplication.objects.get(email=data)
                if data not in stu_registrations:
                    if student_application.is_approved:
                        return data
                    else:
                        raise ValidationError('Your application is not approved.')
                else:
                    raise ValidationError('This email is already used.')
            else:
                raise ValidationError("Email doesn't match with your application email. Please check")
        else:
            raise ValidationError('Student Registrations are closed.')
    

class TestForm(forms.ModelForm):
    class Meta:
        model = StudentApplication
        fields = '__all__'

student_info/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic.edit import FormView, CreateView
from .forms import StudentApplicationForm, StudentRegistrationForm, StudentProfileForm
from auth_app.forms import UserForm
from .models import StudentApplication, StudentProfile, Department, GENDER, Nationality_Choices
from auth_app.models import MyUser
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from django.http import HttpResponse
from .mixins import StudentRegistrationMixin
from django.views.generic import ListView
# from django.views.generic.detail import SingleObjectMixin
from django.views import View
from staff_info.models import StaffProfile
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from auth_app.mixins import StudentLoginRequiredMixin


# class LoginRequiredMixin(object):
#     @classmethod
#     def as_view(cls):
#         return login_required(super(LoginRequiredMixin, cls).as_view())

class StudentApplicationPage(CreateView):
    model = StudentApplication
    form_class = StudentApplicationForm
    template_name = 'student_info/application_form.html'
    success_url = reverse_lazy('college:index')


class StudentRegistrationPage( StudentRegistrationMixin ,FormView):
    form_class = StudentRegistrationForm 
    template_name = 'student_info/registration_form.html'

    def get_context_data(self, *args, **kwargs):
        """
        Getting the context from the super class and adding additional content of
        Nationality Gender choices for the select tag
        """
        context_data = super().get_context_data(*args, **kwargs)
        context_data['nationality'] = Nationality_Choices
        context_data['gender'] = GENDER
        return context_data
    
    def form_valid(self, form):
        """
        After validating the form creating student_profile by sending the form data and request to the 
        StudentRegistrationMixin => create_stu_profile(request, form) 
        """
        # import ipdb;ipdb.set_trace(context=15)
        self.create_stu_profile(self.request, form)
        return redirect(reverse('college:index'))
    

# @method_decorator(login_required(login_url=reverse('authentication:stu_login')), name='dispatch')
class StudentDashboard(StudentLoginRequiredMixin,View):
    
    
    def get(self, request):
        context = {'profile':StudentProfile.objects.get(user=request.user)}
        print(context)
        return render(request, 'student_info/dashboard.html', context=context)
    
    
# @method_decorator(login_required(login_url=reverse('authentication:stu_login')), name='dispatch')
class StudentListView(ListView):
    model = StudentProfile
    template_name = 'student_info/dept_students.html'
    context_object_name = 'students'

    def get_queryset(self):
        return self.model.objects.filter(application__department__code = self.kwargs['dept'])
    


# @method_decorator(login_required(login_url=reverse('authentication:stu_login')), name='dispatch')
class StaffList(View):
    def get(self, *args, **kwargs):
        staff = StaffProfile.objects.filter(department__code=kwargs['dept'])
        return render(self.request, 'student_info/d_staff.html', {'staff_list':staff})


def success(request):
    print('*'*50)
    print(request.POST)
    print('*'*50)
    print(request.FILES)
    print('*'*50)
    return HttpResponse('Success')
        

student_info/templates/student_info/application_form.html
<form method="post" action=".">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Apply" >
</form>
<br>
<hr><br>
<a href="{% url 'college:index' %}">Cancel Apply</a>

{% if form.errors %}
  <tr>
    <td colspan="2">
      {{ form.errors }}
      {% if not form.fields %}
        {% for field in form.hidden_fields %}{{ field }}{% endfor %}
      {% endif %}
    </td>
  </tr>
{% endif %}
{% for field, errors in form.fields %}
  <tr{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    <th>{% if field.label %}{{ field.label_tag }}{% endif %}</th>
    <td>
      {{ errors }}
      {{ field }}
      {% if field.help_text %}
        <br>
        <span class="helptext">{{ field.help_text|safe }}</span>
      {% endif %}
      {% if forloop.last %}
        {% for h_field in form.hidden_fields %}{{ h_field }}{% endfor %}
      {% endif %}
    </td>
  </tr>
{% endfor %}
{% if not form.fields and not form.errors %}
  {% for field in form.hidden_fields %}{{ field }}{% endfor %}
{% endif %}

student_info/templates/student_info/d_staff.html
{% if staff_list %}
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Mobile Number</th>
                <th>Department</th>
            </tr>
        </thead>
        <tbody>
            {% for staff in staff_list  %}
                <tr>
                    <td>{{staff.name}}</td>
                    <td>{{staff.user.email}}</td>
                    <td>{{staff.user.mobile_number}}</td>
                    <td>{{staff.department}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <h1>No staff are available.</h1>
{% endif %}

<br><hr><br>
<a href="{% url 'student:stu_dashboard' %}">Back</a><br>
<a href="{% url 'authentication:stu_logout' %}">Logout</a>

student_info/templates/student_info/dashboard.html
<div class="container">
    <div class="row">
        <div class="col-6">
            <table>
                <tr>
                    <td>
                        <strong>Name</strong>
                    </td>
                    <td>
                        <p>{{profile.application.name}}</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>Email</strong>
                    </td>
                    <td>
                        <p>{{profile.application.email}}</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>SSC</strong>
                    </td>
                    <td>
                        <p>{{profile.application.ssc}}</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>Intermediate</strong>
                    </td>
                    <td>
                        <p>{{profile.application.intermediate}}</p>
                    </td>
                </tr>
            </table>
        </div>
        <div class="col-6">
            <table>
                <tr>
                    <td>
                        <strong>Department</strong>
                    </td>
                    <td>
                        <p>{{profile.application.department}}</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>Gender</strong>
                    </td>
                    <td>
                        <p>{{profile.gender}}</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>Nationality</strong>
                    </td>
                    <td>
                        <p>{{profile.nationality}}</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>Date of Birth</strong>
                    </td>
                    <td>
                        <p>{{profile.dob}}</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>Profile Picture</strong>
                    </td>
                    <td>
                        <img src="{{profile.profile_pic.url}}" class="imgage-fluid" style="width: 100px; height: 70px;" >
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="">
    <button><a href="{% url 'student:dept_students' profile.application.department %}">Student List</a></button><br>
    <button>
        <a href="{% url 'student:staff' %}">Staff List</a>
    </button><br>
    <button><a href="{% url 'authentication:stu_logout' %}">Logout</a></button><br>
</div>

student_info/templates/student_info/dept_students.html
<table>
    <thead>
        <tr>
            <div class="container">
                <div class="row">
                    <div class="col-4">
                        <td>
                            Roll No
                        </td>
                    </div>
                    <div class="col-4">
                        <td>
                            Email
                        </td>
                    </div>
                    <div class="col-4">
                        <td>
                            Name
                        </td>
                    </div>
                </div>
            </div>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
            <tr>
                <div class="container">
                    <div class="row">
                        <div class="col-4">
                            <td>
                                {{student.id}}
                            </td>
                        </div>
                        <div class="col-4">
                            <td>
                                {{student.application.email}}
                            </td>
                        </div>
                        <div class="col-4">
                            <td>
                                {{student.application.name}}
                            </td>
                        </div>
                    </div>
                </div>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="container">
    <button><a href="{% url 'student:stu_dashboard' %}">Back</a> </button><br>
    <button><a href="{% url 'authentication:stu_logout' %}">Logout</a> </button>
</div>

student_info/templates/student_info/registration_form.html
{% if form.errors %}{{form.errors}}{% endif %}
{{department_list}}
<form method="POST" enctype="multipart/form-data" action=".">
    {% csrf_token %}
    Email : <input type="email" name="email"><br>
    Gender : <select name="gender">
        {% for code,gen in gender %}
            <option value="{{code}}">{{gen}}</option>
        {% endfor %}
    </select><br>
    DOB : <input type="date" name="dob" ><br>
    Nationality : <select name="nationality">
        {% for code, nation in nationality %}
            <option value="{{code}}">{{nation}}</option>
        {% endfor %}
    </select><br>
    Profile Pic : <input type="file" name="profile_pic"><br>
    Mobile Number : <input type="number" name="mobile_number"><br>
    Password : <input type="password" name="password"><br>
    <input type="submit" value="Register">
</form>
<br><hr><br>
<a href="{% url 'college:index' %}">Cancel Registration</a>