auth_app/urls.py
from django.urls import path
from . import views


app_name = 'authentication'
urlpatterns = [
    path('student_login/', views.StudentLoginForm.as_view(), name='stu_login'),
    path('student_logout/', views.StudentLogout.as_view(), name='stu_logout'),
    path('staff/login/', views.StaffLoginForm.as_view(), name='staff_login'),
    path('staff/logout/', views.StaffLogout.as_view(), name='staff_logout'),
]

college/urls.py
from django.urls import path
from college import views

app_name = 'college'
urlpatterns = [
    path('index/', views.IndexPage.as_view(), name='index'),
    path('departments/', views.DepartmentList.as_view(), name='depts'),
    path('<str:dept>/department/', views.DepartmentStudentView.as_view(), name='d_std'),



    path('download-users-csv/', views.download_user_details_csv, name='download_users_csv'),
    path('browse_csv/', views.browse_csv, name='browse_csv'),
    path('upload_csv/', views.upload_csv, name='upload_csv'),
]

college_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('college.urls')),
    path('auth/', include('auth_app.urls')),
    path('student/', include('student_info.urls')),
    path('staff/', include('staff_info.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff_info/urls.py
from django.urls import path
from . import views


app_name = 'staff'
urlpatterns = [
    path('registration/', views.StaffRegistrationPage.as_view(), name='staff_reg'),
    path('dashboard/', views.StaffDetailView.as_view(), name='staff_detail'),
    path('staff_list/', views.StaffListView.as_view(), name='staff_list'),
]

staff_info/models.py
from django.db import models
from student_info.models  import Department, Nationality_Choices
from auth_app.models import MyUser


class StaffProfile(models.Model):
    user = models.OneToOneField(MyUser, on_delete= models.CASCADE)
    profile_pic = models.ImageField(upload_to='Staff Profiles')
    dob = models.DateTimeField()
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    experience = models.IntegerField()
    qualification = models.CharField(max_length=100)

    def __str__(self):
        return self.user.email

staff_info/forms.py
from django import forms
from .models import StaffProfile
from auth_app.models import MyUser
from django.core.exceptions import ValidationError
from student_info.models import Department


class StaffRegistrationForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    dob = forms.DateField()
    experience = forms.CharField()
    qualification = forms.CharField()
    department = forms.ChoiceField( widget=forms.Select,
        choices = [(code[0], code[0]) for code in Department.objects.all().values_list('code')]
    )
    profile_pic =forms.ImageField()
    mobile_number = forms.IntegerField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_email(self):
        email_data = self.cleaned_data['email']
        user_objects = MyUser.objects.all().values_list('email')
        staff = [email[0] for email in user_objects] if user_objects else []
        if email_data not in staff:
            return email_data
        else:
            raise ValidationError('Email already exists. Kindly use another email.')


class  StaffProfileForm(forms.ModelForm):
    class Meta:
        model = StaffProfile
        fields = ['profile_pic', 'dob', 'qualification', 'experience']

staff_info/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from .forms import StaffRegistrationForm, StaffProfileForm
from auth_app.forms import UserForm
from student_info.models import Department
from auth_app.models import MyUser
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from .models import StaffProfile
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from auth_app.mixins import StaffLoginRequiredMixin
from django.utils.decorators import method_decorator


class StaffRegistrationPage(FormView):
    form_class = StaffRegistrationForm
    template_name = 'staff_info/staff_registration.html'

    def form_valid(self, form):
        dept = Department.objects.get(code=form.cleaned_data['department']) 
        user = UserForm(form.cleaned_data)
        if user.is_valid():
            my_user = MyUser.objects.create_user(**user.cleaned_data)
            data = form.cleaned_data
            data.pop('department')
            staff = StaffProfileForm(data, files=self.request.FILES)
            if staff.is_valid():
                # StaffProfile.objects.create(**dict(self.request.FILES),**staff.cleaned_data,user=my_user, department =dept)
                staff_profile = staff.save(commit=False)
                staff_profile.user = my_user
                staff_profile.department = dept
                staff_profile.save()
                return redirect(reverse('authentication:staff_login'))
            else:
                errors = staff.errors.as_data()
                return render(self.request, self.template_name, {'form':form, 'errors':errors})
        else:
            form.errors = user.errors
            return render(self.request, self.template_name, {'form':form})


class StaffDetailView(StaffLoginRequiredMixin, View):
    def get(self, request):
        context = {'profile':StaffProfile.objects.get(user=request.user)}
        print(context)
        return render(request, 'staff_info/dashboard.html', context=context)
    

@method_decorator(login_required(login_url=reverse_lazy('authentication:staff_login')), name='dispatch')
class StaffListView( ListView):
    model = StaffProfile
    template_name = 'staff_info/staff_list.html'
    context_object_name = 'staffs'

staff_info/templates/staff_info/dashboard.html
<div class="container">
    <div class="row">
        <div class="col-6">
            <table>
                <tr>
                    <td>
                        <strong>Name</strong>
                    </td>
                    <td>
                        <p>{{profile.name}}</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>Email</strong>
                    </td>
                    <td>
                        <p>{{profile.user.email}}</p>
                    </td>
                </tr>
            </table>
        </div>
        <div class="col-6">
            <table>
                <tr>
                    <td>
                        <strong>Department</strong>
                    </td>
                    <td>
                        <p>{{profile.department}}</p>
                    </td>
                </tr>
                
                <tr>
                    <td>
                        <strong>Date of Birth</strong>
                    </td>
                    <td>
                        <p>{{profile.dob}}</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>Profile Picture</strong>
                    </td>
                    <td>
                        <img src="{{profile.profile_pic.url}}" class="imgage-fluid" style="width: 100px; height: 70px;" >
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="">
    <button><a href="{% url 'college:depts' %}">Student List</a></button><br>
    <button><a href="{% url 'staff:staff_list' %}">Staff List</a></button><br>
    <button><a href="{% url 'authentication:staff_logout' %}">Logout</a></button><br>
</div>

staff_info/templates/staff_info/staff_list.html
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Department</th>
            <th>Email</th>
            <th>Mobile_number</th>
        </tr>
    </thead>
    <tbody>
        {% for staff in staffs %}
            <tr>
                <td>{{staff.name}}</td>
                <td>{{staff.department}}</td>
                <td>{{staff.user.email}}</td>
                <td>{{staff.user.mobile_number}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'staff:staff_detail' %}">Back</a><br>
<a href="{% url 'authentication:staff_logout' %}">Logout</a>

staff_info/templates/staff_info/staff_registration.html
<div class="container">
    <form method="post" enctype="multipart/form-data" action=".">
        {% if errors %}{{errors}}{% endif %}
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
</div>